version: "3.8"

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: erp_root_password
      MYSQL_DATABASE: erp_kmm_project
    volumes:
      - db_data:/var/lib/mysql
      # Folder ini untuk import .sql otomatis saat pertama kali menyala
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  backend:
    build:
      context: ./be-express-erp
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - ./be-express-erp/.env
      # 👈 TAMBAHKAN VOLUMES INI
    volumes:
      - ./be-express-erp/uploads:/app/uploads
    restart: always
    depends_on:
      - db

  frontend:
    build:
      context: ./fe-nextjs-erp
    ports:
      - "3000:3000"
    env_file:
      - ./fe-nextjs-erp/.env
    restart: always

volumes:
  db_data:
